/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {

      BinarySearchTree<Integer> newTree = new BinarySearchTree<>();

      newTree.add(50);
      newTree.add(45);
      newTree.add(60);
      newTree.add(75);
      newTree.add(21);

//      System.out.println(newTree.contain(80));
//      System.out.println(newTree.contain(70));

//      System.out.println(newTree.getMax());
//      System.out.println(newTree.breadthFirst(newTree));

      System.out.println(newTree.sumOfOdds());

    }







}
