/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  public void addVertex(){

    Graph graph = new Graph();

    graph.addVertex("Hatem");
    graph.addVertex("Tareq");

    assertNotNull(graph.getVertices());
    assertEquals(2,graph.size());
  }

  @Test
  public void addEdge(){

    Graph graph = new Graph();

    graph.addVertex("Hatem");
    graph.addVertex("Tareq");
    graph.addEdge("Hatem", "Tareq");

    assertEquals("Vertex{label='Hatem', weight=0}[Vertex{label='Tareq', weight=0}]Vertex{label='Tareq', weight=0}[Vertex{label='Hatem', weight=0}]", graph.printGraph());
  }

  @Test
  public void vertexNeighbors(){

    Graph graph = new Graph();

    graph.addVertex("Hatem");
    graph.addVertex("Tareq");
    graph.addVertex("Doaa");
    graph.addVertex("Mohammad");
    graph.addEdge("Hatem", "Doaa");
    graph.addEdge("Hatem", "Tareq");
    graph.addEdge("Mohammad", "Tareq");

    assertEquals("[Vertex{label='Doaa', weight=0}, Vertex{label='Tareq', weight=0}]",graph.getNeighbors("Hatem").toString());
    assertEquals("[Vertex{label='Tareq', weight=0}]", graph.getNeighbors("Mohammad").toString());

  }

  @Test
  public void emptyGraph(){

    Graph graph = new Graph();
    assertEquals(0,graph.size());
    assertEquals("[]", graph.getVertices().toString());
  }
  //    <<<Code Challenge 36 >>
  @Test
  public void breadthFirst(){

    Graph graph1 = new Graph();

    graph1.addVertex("Hatem");
    graph1.addVertex("Tareq");
    graph1.addVertex("Doaa");
    graph1.addVertex("Mohammad");
    graph1.addVertex("Osaid");
    graph1.addVertex("Naim");

    graph1.addEdge("Hatem", "Tareq");
    graph1.addEdge("Tareq", "Doaa");
    graph1.addEdge("Tareq", "Mohammad");
    graph1.addEdge("Doaa", "Osaid");
    graph1.addEdge("Doaa", "Naim");
    graph1.addEdge("Doaa", "Mohammad");
    graph1.addEdge("Mohammad", "Naim");
    graph1.addEdge("Osaid", "Naim");


    assertEquals("[Hatem, Tareq, Doaa, Mohammad, Osaid, Naim]", graph1.breadthTraverse("Hatem").toString());
  }

  @Test
  public void breadthFirstOneVertex(){

    Graph graph1 = new Graph();

    graph1.addVertex("Hatem");
    assertEquals("[Hatem]",graph1.breadthTraverse( "Hatem").toString());
  }

  //    THIS TEST FOR THREE VERTICES AND ONE OF THEM DID NOT CONNECT WITH THE OTHER TWO VERTICES
  @Test
  public void breadthFirstTest(){

    Graph graph1 = new Graph();

    graph1.addVertex("Hatem");
    graph1.addVertex("Tareq");
    graph1.addVertex("Doaa");

    graph1.addEdge("Hatem", "Tareq");

    assertEquals("[Hatem, Tareq]",graph1.breadthTraverse( "Hatem").toString());
  }


}
