/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {

        LinkedList list1 = new LinkedList();
      LinkedList list2 = new LinkedList();
      LinkedList list3 = new LinkedList();
//        linkedList.insert("a");
//      linkedList.insert("b");
//      linkedList.insert("c");
//      linkedList.insert("d");
//      linkedList.insert("e");
//
//
//      System.out.println(linkedList.include("c"));
//      System.out.println(linkedList.include("x"));
//
//      linkedList.append("R");
//      linkedList.insertBefore("c","C");
//
//      linkedList.insertAfter("b","B");

      list1.append("A");
      list1.append("B");
      list1.append("C");
      list1.append("D");
      list1.append("E");
      list1.append("F");

      list2.append("1");
      list2.append("2");
      list2.append("3");
      list2.append("4");

      System.out.println(list3.zipLists(list1,list2));




    }


}
